from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"

MODEL_NAME = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-ada-002"

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

COMPLIANCE_TEMPERATURE = 0.0
COMPLIANCE_MAX_TOKENS = 300

RELOCATION_TEMPERATURE = 0.4
RELOCATION_MAX_TOKENS = 450

EXTRACTION_TEMPERATURE = 0.0

RAG_SEARCH_K = 2
BRAVE_SEARCH_COUNT = 3

BRAVE_TIMEOUT = 15
OPENAI_TIMEOUT = 30

RETRY_OPENAI_ATTEMPTS = 3
RETRY_BRAVE_ATTEMPTS = 2
RETRY_MIN_WAIT = 2
RETRY_MAX_WAIT = 10
